name: cedar_flutter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  grpc: ^3.2.3
  protobuf: ^3.0.0
  sprintf: ^7.0.0
  fixnum: 1.1.0
  numberpicker: ^2.1.2
  settings_ui: ^2.0.2
  provider: ^6.1.1
  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/tiles/0/0/
    - assets/tiles/1/0/
    - assets/tiles/1/1/
    - assets/tiles/2/0/
    - assets/tiles/2/1/
    - assets/tiles/2/2/
    - assets/tiles/2/3/
    - assets/tiles/3/0/
    - assets/tiles/3/1/
    - assets/tiles/3/2/
    - assets/tiles/3/3/
    - assets/tiles/3/4/
    - assets/tiles/3/5/
    - assets/tiles/3/6/
    - assets/tiles/3/7/
    - assets/tiles/4/0/
    - assets/tiles/4/1/
    - assets/tiles/4/2/
    - assets/tiles/4/3/
    - assets/tiles/4/4/
    - assets/tiles/4/5/
    - assets/tiles/4/6/
    - assets/tiles/4/7/
    - assets/tiles/4/8/
    - assets/tiles/4/9/
    - assets/tiles/4/10/
    - assets/tiles/4/11/
    - assets/tiles/4/12/
    - assets/tiles/4/13/
    - assets/tiles/4/14/
    - assets/tiles/4/15/
    - assets/tiles/5/0/
    - assets/tiles/5/1/
    - assets/tiles/5/2/
    - assets/tiles/5/3/
    - assets/tiles/5/4/
    - assets/tiles/5/5/
    - assets/tiles/5/6/
    - assets/tiles/5/7/
    - assets/tiles/5/8/
    - assets/tiles/5/9/
    - assets/tiles/5/10/
    - assets/tiles/5/11/
    - assets/tiles/5/12/
    - assets/tiles/5/13/
    - assets/tiles/5/14/
    - assets/tiles/5/15/
    - assets/tiles/5/16/
    - assets/tiles/5/17/
    - assets/tiles/5/18/
    - assets/tiles/5/19/
    - assets/tiles/5/20/
    - assets/tiles/5/21/
    - assets/tiles/5/22/
    - assets/tiles/5/23/
    - assets/tiles/5/24/
    - assets/tiles/5/25/
    - assets/tiles/5/26/
    - assets/tiles/5/27/
    - assets/tiles/5/28/
    - assets/tiles/5/29/
    - assets/tiles/5/30/
    - assets/tiles/5/31/
    - assets/tiles/6/0/
    - assets/tiles/6/1/
    - assets/tiles/6/2/
    - assets/tiles/6/3/
    - assets/tiles/6/4/
    - assets/tiles/6/5/
    - assets/tiles/6/6/
    - assets/tiles/6/7/
    - assets/tiles/6/8/
    - assets/tiles/6/9/
    - assets/tiles/6/10/
    - assets/tiles/6/11/
    - assets/tiles/6/12/
    - assets/tiles/6/13/
    - assets/tiles/6/14/
    - assets/tiles/6/15/
    - assets/tiles/6/16/
    - assets/tiles/6/17/
    - assets/tiles/6/18/
    - assets/tiles/6/19/
    - assets/tiles/6/20/
    - assets/tiles/6/21/
    - assets/tiles/6/22/
    - assets/tiles/6/23/
    - assets/tiles/6/24/
    - assets/tiles/6/25/
    - assets/tiles/6/26/
    - assets/tiles/6/27/
    - assets/tiles/6/28/
    - assets/tiles/6/29/
    - assets/tiles/6/30/
    - assets/tiles/6/31/
    - assets/tiles/6/32/
    - assets/tiles/6/33/
    - assets/tiles/6/34/
    - assets/tiles/6/35/
    - assets/tiles/6/36/
    - assets/tiles/6/37/
    - assets/tiles/6/38/
    - assets/tiles/6/39/
    - assets/tiles/6/40/
    - assets/tiles/6/41/
    - assets/tiles/6/42/
    - assets/tiles/6/43/
    - assets/tiles/6/44/
    - assets/tiles/6/45/
    - assets/tiles/6/46/
    - assets/tiles/6/47/
    - assets/tiles/6/48/
    - assets/tiles/6/49/
    - assets/tiles/6/50/
    - assets/tiles/6/51/
    - assets/tiles/6/52/
    - assets/tiles/6/53/
    - assets/tiles/6/54/
    - assets/tiles/6/55/
    - assets/tiles/6/56/
    - assets/tiles/6/57/
    - assets/tiles/6/58/
    - assets/tiles/6/59/
    - assets/tiles/6/60/
    - assets/tiles/6/61/
    - assets/tiles/6/62/
    - assets/tiles/6/63/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
